embedding:
  name: nlpl_word2vec_it_frozen
  path: embeddings/vec/nlpl_it_word2vec.vec
  binary: false
  dim: 100
  lowercase_lookup: true
  normalize_vectors: false
  oov_strategy: random
  oov_scale: 0.05
