model:
  name: final_charcnn_bilstm_crf_entity_weighted

  # Embeddings
  freeze_word_embeddings: true
  word_dropout: 0.05

  # CharCNN
  use_charcnn: true
  char_embedding_dim: 30
  char_cnn_filters: 50
  char_cnn_kernel_size: 3
  char_dropout: 0.10

  # BiLSTM
  lstm_hidden_dim: 256
  lstm_num_layers: 1
  lstm_dropout: 0.0
  bidirectional: true

  # Classifier
  classifier_dropout: 0.30

  # CRF
  use_crf: true

  # Auxiliary weighted emission loss
  use_auxiliary_ce_loss: true

  # Quanto pesa la CE rispetto al CRF
  auxiliary_ce_weight: 0.1

  # Pesi delle classi
  o_loss_weight: 1.0
  entity_loss_weight: 2.0